"""
risk_engine/ppe_violations.py
==============================
In-memory store for structured PPE violation events generated by the Phase 7C
CCTV camera panel when a worker is detected without required PPE.

Design notes
------------
- Events are stored in-memory (like LIVE_CCTV_STATE) and lost on server restart.
  For production persistence, add a PPEViolationLog SQLAlchemy model to db/models.py.
- Capped at MAX_EVENTS to prevent unbounded growth in demo sessions.
- Thread-safe via a threading.Lock for concurrent FastAPI request handling.

PPE detection honesty
---------------------
The current Coco-SSD model has 80 generic COCO classes and does NOT include
any PPE-specific class (hard hat, safety vest, face mask, etc.).
All violation events currently originate from the "Simulate Hard Hat Violation"
manual override toggle in the CCTVPanel UI.
Events are tagged with detection_method='manual_override' to make this explicit.

A production deployment would replace/augment Coco-SSD with a custom-trained
YOLO model fine-tuned on construction/industrial PPE datasets (e.g. HardHatWorkers
dataset from Roboflow) to enable real model-inferred detection.
"""

from __future__ import annotations
import threading
from datetime import datetime
from typing import List, Dict, Any, Optional

MAX_EVENTS = 200

# Thread lock for safe concurrent access
_lock = threading.Lock()

# Event store — list of dicts, newest first
PPE_VIOLATION_EVENTS: List[Dict[str, Any]] = []

# Auto-incrementing ID counter
_next_id = 1


def record_violation(
    zone_id: str,
    zone_name: str,
    plant_id: str,
    ppe_items_missing: List[str],
    confidence_pct: float,
    detection_method: str,
    risk_score_at_time: Optional[float] = None,
) -> Dict[str, Any]:
    """
    Create and store a new PPE violation event.

    Parameters
    ----------
    zone_id            : Zone identifier (e.g. 'zone_ca')
    zone_name          : Human-readable zone name (e.g. 'Charging Platform')
    plant_id           : Plant identifier (e.g. 'plant_coke_oven')
    ppe_items_missing  : List of PPE items not worn (e.g. ['hard_hat'])
    confidence_pct     : Model confidence 0–100. Pass 0 for manual_override events.
    detection_method   : 'manual_override' or 'model_inferred'
    risk_score_at_time : Current zone risk score when the event was recorded (optional)

    Returns
    -------
    The newly created event dict.
    """
    global _next_id

    event: Dict[str, Any] = {
        "id":                  _next_id,
        "zone_id":             zone_id,
        "zone_name":           zone_name,
        "plant_id":            plant_id,
        "timestamp":           datetime.now().isoformat(),
        "ppe_items_missing":   ppe_items_missing,
        "confidence_pct":      confidence_pct,
        "detection_method":    detection_method,   # 'manual_override' | 'model_inferred'
        "status":              "open",             # open | acknowledged | resolved
        "risk_score_at_time":  risk_score_at_time,
    }

    with _lock:
        _next_id += 1
        # Prepend so newest is first
        PPE_VIOLATION_EVENTS.insert(0, event)
        # Enforce cap
        if len(PPE_VIOLATION_EVENTS) > MAX_EVENTS:
            PPE_VIOLATION_EVENTS.pop()

    return event


def get_violations(
    plant_id: Optional[str] = None,
    status: Optional[str] = None,
    limit: int = 100,
) -> List[Dict[str, Any]]:
    """
    Return violation events, newest first.

    Parameters
    ----------
    plant_id : If provided, filter to this plant.
    status   : If provided, filter by 'open' | 'acknowledged' | 'resolved'.
    limit    : Max events to return (default 100).
    """
    with _lock:
        results = list(PPE_VIOLATION_EVENTS)  # shallow copy

    if plant_id:
        results = [e for e in results if e["plant_id"] == plant_id]
    if status:
        results = [e for e in results if e["status"] == status]

    return results[:limit]


def update_status(event_id: int, new_status: str) -> Optional[Dict[str, Any]]:
    """
    Update the status of a violation event in-place.

    Parameters
    ----------
    event_id   : The numeric ID of the event to update.
    new_status : 'acknowledged' or 'resolved'

    Returns
    -------
    The updated event dict, or None if not found.
    """
    with _lock:
        for event in PPE_VIOLATION_EVENTS:
            if event["id"] == event_id:
                event["status"] = new_status
                return dict(event)
    return None
